services:
  # Наш перший генератор
  generator-barista:
    build: ./micro-barista  # Вказуємо папку, де лежить Dockerfile
    container_name: omnilog-barista
    restart: unless-stopped # Якщо контейнер впаде, Docker сам його перезапустить!
  generator-smart-home:
    build: ./smart-home
    container_name: omnilog-smart-home
    restart: unless-stopped
  localstack:
    image: localstack/localstack:latest
    container_name: omnilog-aws-mock
    ports:
      - "4566:4566" # Це порт, на якому висить фейковий API AWS
    environment:
      - SERVICES=ec2,s3,iam # Кажемо йому імітувати тільки потрібні нам сервіси
      - DOCKER_HOST=unix:///var/run/docker.sock